# Generated by Django 3.1.3 on 2023-02-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230204_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
